gleb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('medshows.urls')),
    path('', include('parser.urls')),
    path('', include('users.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

medshows/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('medshows/', views.MedShowListView.as_view(), name='medshow'),
    path('medshows/create/', views.create_medshow, name='medshows_create'),
    path('medshows/<int:id>/', views.MedShowsDetailView.as_view(), name='medshows_detail'),
    path('medshows/update/<int:id>/', views.update_medshow, name='medshows_update'),
    path('medshows/delete/<int:id>/', views.delete_medshow, name='medshows_delete'),
]

parser/urls.py
from django.urls import path
from . import views

app_name = 'parse'
urlpatterns = [
    path('med-aparment-list/', views.ParserView.as_view(), name='med_apartment_list'),
    path('parser/', views.ParserFormView.as_view(), name='parse_func'),
]

users/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('log_in/', views.log_in_user, name='log_in'),
    path('log_out/', views.log_out_user, name='logout_user'),
    path('registration/', views.register_user, name='registration'),
]

medshows/models.py
import os
from django.db import models
from django.conf import settings

class Type(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class MedicalShows(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    images = models.ImageField(upload_to=os.path.join(settings.MEDIA_ROOT))
    type = models.CharField(max_length=100)
    timeadd = models.DateTimeField()

    def __str__(self):
        return self.title

parser/models.py
from django.db import models


class AllMedApartment(models.Model):
    name = models.CharField(max_length=255)
    image = models.ImageField(upload_to='')

    def __str__(self):
        return self.name

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    pass

medshows/forms.py
from django import forms
from . import models

class MedShowForm(forms.ModelForm):
    class Meta:
        model = models.MedicalShows
        fields = "__all__"

parser/forms.py
from . import parser, models
from django import forms


class ParserForm(forms.Form):
    MEDIA_CHOISES = (
        ('MEDIK', 'MEDIK'),
    )
    media_type = forms.ChoiceField(choices=MEDIA_CHOISES)

    class Meta:
        fields = [
            'media_type',
        ]
        
    def parser_data(self):
        if self.data['media_type'] == 'MEDIK':
            film_parser = parser.parser()
            for i in film_parser:
                models.AllMedApartment.objects.create(**i)

medshows/views.py
import os

from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from . import models
from django.conf import settings


def redirect(request):
    return HttpResponseRedirect(reverse('medshow'))


class MedShowListView(generic.ListView):
    template_name = 'medshows.html'
    queryset = models.MedicalShows.objects.all()


class MedShowsDetailView(generic.DetailView):
    template_name = 'medshow_detail.html'
    queryset = models.MedicalShows.objects.all()

    def get_object(self, **kwargs):
        medshows_id = self.kwargs.get('id')
        return get_object_or_404(models.MedicalShows, id=medshows_id)


def create_medshow(request):
    if request.method == 'POST':
        title = request.POST['title']
        description = request.POST['description']
        images = request.FILES['images']
        medshow_type = request.POST['type']
        timeadd = request.POST['timeadd']

        new_medshow = models.MedicalShows.objects.create(
            title=title,
            description=description,
            images=images,
            type=medshow_type,
            timeadd=timeadd
        )
        new_medshow.save()
        return redirect('medshow')

    medshow_types = models.Type.objects.all()
    context = {
        'medshow_types': medshow_types
    }
    return render(request, 'medshow_create.html', context)


def update_medshow(request, id):
    medshow = get_object_or_404(models.MedicalShows, id=id)
    medshow_types = models.Type.objects.all()

    if request.method == 'POST':
        title = request.POST['title']
        description = request.POST['description']
        images = request.FILES['images']
        medshow_type = request.POST['type']
        timeadd = request.POST['timeadd']

        medshow.title = title
        medshow.description = description
        medshow.images = images
        medshow.type = medshow_type
        medshow.timeadd = timeadd
        medshow.save()
        return redirect('medshow')

    context = {
        'medshow': medshow,
        'medshow_types': medshow_types,
    }
    return render(request, 'medshow_update.html', context)


def delete_medshow(request, id):
    medshow = get_object_or_404(models.MedicalShows, id=id)
    medshow.delete()
    return redirect('medshow')

parser/views.py
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import ListView, FormView
from . import models, forms


class ParserView(ListView):
    model = models.AllMedApartment
    template_name = 'med_apartment_list.html'

    def get_queryset(self):
        return models.AllMedApartment.objects.all()


class ParserFormView(FormView):
    template_name = 'parser.html'
    form_class = forms.ParserForm

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.parser_data()
            return redirect(reverse('medshow'))
            # return redirect(reversed("parse:list_objects"))
        else:
            return super(ParserFormView, self).post(request, *args, **kwargs)

users/views.py
from django.contrib.auth import login, logout
from django.shortcuts import render, redirect
from django.urls import reverse

from . import models


def register_user(request):

    if request.method == 'POST':
        email = request.POST['email']
        username = request.POST['login']
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        password = request.POST['password']
        re_password = request.POST['re-password']
        if password != re_password:
            return render(request, "registration.html", {'error': True})

        new_user = models.CustomUser.objects.create(
            email=email,
            username=username,
            first_name=first_name,
            last_name=last_name,
            password=password,
        )
        new_user.save()
        return redirect(reverse('medshow'))
    return render(request, "registration.html", {'error': False})


def log_in_user(request):

    error = False
    context = {'error': error}

    if request.method == 'POST':
        username = request.POST['login']
        password = request.POST['password']
        users = models.CustomUser.objects.all()
        user = None
        for i in users:
            if i.username == username and i.password == password:
                user = i
        if user:
            login(request, user)
            return redirect(reverse('medshow'))
        error = True
        context = {'error': error}

    return render(request, "login.html", context)


def log_out_user(request):
    if request.user.is_authenticated:
        logout(request)
    return redirect(reverse('medshow'))

templates/default.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width-device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

</head>
<body>
    {% block content %}{% endblock %}
    <div class="album py-5 bg-dark">
        <footer class="my-5 pt-5 text-muted text-center text-small">
            <p class="mb-1 text-light">INAI.KG</p>
        </footer>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
</body>
</html>

templates/login.html
{% extends 'default.html' %}
{% block content %}
<div class="album py-5 bg-secondary">
  <div class="container">
    <br><br><br>
      <div class="row">
        <div class="col-md-8 order-md-1">
        {% if error %}
            <div class="alert alert-danger" role="alert">Wrong login or password. Please re-enter.</div>
        {% endif %}
          <h4 class="mb-3">Log in</h4>
          <form action="{% url 'log_in' %}" class="needs-validation" novalidate method="POST">
            {% csrf_token %}
            <div class="row">
              <div class="col-md-6 mb-3">
                <label for="login">Login</label>
                <input type="text" class="form-control" id="login" name="login" placeholder="" required>
                <div class="invalid-feedback">
                  Valid username is required.
                </div>
              </div>
              <br>
              <div class="col-md-6 mb-3">
                <label for="password">Password</label>
                <input type="password" class="form-control" id="password" name="password" placeholder="" required>
                <div class="invalid-feedback">
                  Valid password is required.
                </div>
              </div>
            </div>
            <div class="text">
              <p>Do not have an account? <a href="{% url 'registration' %}" class="link-light">Register</a></p>
            </div>
            <button class="btn btn-primary btn-lg btn-block" type="submit">sign in</button>
          </form>
          <br><br><br><br>
        </div>
      </div>
    </div>
</div>
{% endblock %}

templates/med_apartment_list.html
{% extends 'default.html' %}
{% block content %}
{% for i in object_list %}
    <li>
    <h2>
        {{i.name}}
    </h2>
        <img src="{{i.image.url}}" alt="">
    </li>
{%endfor%}
{% endblock %}

templates/medshow_create.html
{% extends 'default.html' %}

{% block content %}
<div class="album py-5 bg-secondary">
   <div class="container">
      <br><br><br>
      <div class="row">
         <div class="col-md-8 order-md-1">
            <h4 class="mb-3">Create medical show</h4>
            <form action="{% url 'medshows_create' %}" class="needs-validation" novalidate method="POST" enctype="multipart/form-data">
               {% csrf_token %}
               <div class="row">
                  <div class="col-md-6 mb-3">
                     <label for="title">Title</label>
                     <input type="text" class="form-control" id="title" name="title" placeholder="" required>
                  </div>
                  <div class="col-md-6 mb-3">
                     <label for="description">Description</label>
                      <textarea class="form-control" id="description" name="description" placeholder="" required></textarea>
                  </div>
                  <div class="col-md-6 mb-3">
                    <select class="custom-select d-block w-100" name="type" required>
                        {% for type in medshow_types %}
                            <option value="{{ type }}" name="city">{{ type }}</option>
                        {% endfor %}
                    </select>
                  </div>
                  <div class="col-md-6 mb-3">
                     <label for="images">Image</label>
                     <input type="file" class="form-control" id="images" name="images" placeholder="" required>
                  </div>
                  <div class="col-md-6 mb-3">
                     <label for="timeadd">date and time</label>
                     <input type="text" class="form-control" id="timeadd" name="timeadd" placeholder="" required>
                  </div>
               </div>
               <button class="btn btn-primary btn-lg btn-block" type="submit">Create</button>
            </form>
            <br><br><br><br>
         </div>
      </div>
   </div>
</div>
<!-- Bootstrap core JavaScript
   ================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
<script src="../../assets/js/vendor/popper.min.js"></script>
<script src="../../dist/js/bootstrap.min.js"></script>
<script src="../../assets/js/vendor/holder.min.js"></script>
<script>
   // Example starter JavaScript for disabling form submissions if there are invalid fields
   (function() {
     'use strict';
   
     window.addEventListener('load', function() {
       // Fetch all the forms we want to apply custom Bootstrap validation styles to
       var forms = document.getElementsByClassName('needs-validation');
   
       // Loop over them and prevent submission
       var validation = Array.prototype.filter.call(forms, function(form) {
         form.addEventListener('submit', function(event) {
           if (form.checkValidity() === false) {
             event.preventDefault();
             event.stopPropagation();
           }
           form.classList.add('was-validated');
         }, false);
       });
     }, false);
   })();
</script>
{% endblock %}

templates/medshow_detail.html
{% extends 'default.html' %}
{% block title %}main{% endblock %}

{% block content %}
    <div class="py-5 bg-secondary">
       <div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center text-light bg-secondary">
          <h1 class="display-4 font-weight-normal">Обработка медицинских изображений</h1>
          <p class="lead font-weight-normal">INAI.KG</p>
       </div>
       <div class="row justify-content-center">
          <div class="col-md-8 col-lg-6 col-xl-4">
             <div class="card text-black">
                <i class="fab fa-apple fa-lg pt-3 pb-1 px-3"></i>
                <img src="{{ object.images.url }}"
                   class="card-img-top"/>
                <div class="card-body">
                   <div class="text-center">
                      <h3 class="card-title">{{ object.title }}</h3>
                   </div>
                   <div>
                      <h5 class="card-title">Description</h5>
                      <ul>
                         <li>
                            <p class="text-justify">{{ object.description }}</p>
                         </li>
                      </ul>
                   </div>
                   <br>
                   <ul>
                       <li>
                           <small class="text-muted" style="font-size: 110%">
                               {{ object.type }}
                           </small>
                       </li>
                       <li>
                           <small class="text-muted"style="font-size: 110%">
                               {{ object.timeadd }}
                           </small>
                       </li>
                   </ul>
                   <br>
                   <div class="btn-group" style="width: 30%">
                      <a href="{% url 'medshows_update' object.id %}" class="btn btn-success">Редактировать</a>
                      <a href="{% url 'medshows_delete' object.id %}" class="btn btn-danger">Удалить</a>
                   </div>
                </div>
             </div>
          </div>
       </div>
    </div>
{% endblock %}

templates/medshow_update.html
{% extends 'default.html' %}

{% block content %}
<div class="album py-5 bg-secondary">
   <div class="container">
      <br><br><br>
      <div class="row">
         <div class="col-md-8 order-md-1">
            <h4 class="mb-3">Update medical show</h4>
            <form action="{% url 'medshows_update' medshow.id %}" class="needs-validation" novalidate method="POST" enctype="multipart/form-data">
               {% csrf_token %}
               <div class="row">
                  <div class="col-md-6 mb-3">
                     <label for="title">Title</label>
                     <input type="text" class="form-control" id="title" name="title" value="{{ medshow.title }}" placeholder="" required>
                  </div>
                  <div class="col-md-6 mb-3">
                     <label for="description">Description</label>
                     <textarea class="form-control" id="description" name="description" placeholder="" required>{{ medshow.description }}</textarea>
                  </div>
                  <div class="col-md-6 mb-3">
                    <select class="custom-select d-block w-100" name="type" required>
                        {% for type in medshow_types %}
                            {% if type == medshow.type %}
                                <option value="{{ type }}" name="city" selected>{{ type }}</option>
                            {% else %}
                                <option value="{{ type }}" name="city">{{ type }}</option>
                            {% endif %}
                        {% endfor %}
                    </select>
                  </div>
                  <div class="col-md-6 mb-3">
                     <label for="images">Image</label>
                     <input type="file" class="form-control" id="images" name="images" placeholder="" required>
                  </div>
                  <div class="col-md-6 mb-3">
                     <label for="timeadd">date and time</label>
                     <input type="text" class="form-control" id="timeadd" value="{{ medshow.timeadd }}" name="timeadd" placeholder="" required>
                  </div>
               </div>
               <button class="btn btn-primary btn-lg btn-block" type="submit">Update</button>
            </form>
            <br><br><br><br>
         </div>
      </div>
   </div>
</div>
<!-- Bootstrap core JavaScript
   ================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
<script src="../../assets/js/vendor/popper.min.js"></script>
<script src="../../dist/js/bootstrap.min.js"></script>
<script src="../../assets/js/vendor/holder.min.js"></script>
<script>
   // Example starter JavaScript for disabling form submissions if there are invalid fields
   (function() {
     'use strict';
   
     window.addEventListener('load', function() {
       // Fetch all the forms we want to apply custom Bootstrap validation styles to
       var forms = document.getElementsByClassName('needs-validation');
   
       // Loop over them and prevent submission
       var validation = Array.prototype.filter.call(forms, function(form) {
         form.addEventListener('submit', function(event) {
           if (form.checkValidity() === false) {
             event.preventDefault();
             event.stopPropagation();
           }
           form.classList.add('was-validated');
         }, false);
       });
     }, false);
   })();
</script>
{% endblock %}

templates/medshows.html
{% extends 'default.html' %}
{% block title %}main{% endblock %}
{% block content %}
    <div class="album py-5 bg-secondary">
       <div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center text-light bg-secondary">
          <h1 class="display-4 font-weight-normal">Обработка медицинских изображений</h1>
          <p class="lead font-weight-normal">INAI.KG</p>
          <div class="btn-group">
              <a href="{% url 'medshows_create' %}" class="btn btn-dark">Create medshow</a>
              <a href="{% url 'parse:med_apartment_list' %}" class="btn btn-dark">Med Apartments</a>
              <a href="{% url 'parse:parse_func' %}" class="btn btn-dark">Parse</a>
          </div>

       </div>
       <div class="container">
          <div class="row">
             {% for object in object_list %}
                 <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                       <img class="card-img-top" src="{{ object.images.url }}" alt="Card image cap">
                       <div class="card-body">
                          <h3 class="card-text text-center">
                              <a href="{% url 'medshows_detail' object.id %}" class="link-dark">
                                  {{ object.title }}
                              </a>
                          </h3>
                          <p class="card-text">{{ object.description }}</p>
                       </div>
                    </div>
                 </div>
             {% endfor %}
          </div>
       </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="../../assets/js/vendor/popper.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <script src="../../assets/js/vendor/holder.min.js"></script>
    <script>
       Holder.addTheme('thumb', {
         bg: '#55595c',
         fg: '#eceeef',
         text: 'Thumbnail'
       });
    </script>
{% endblock %}

templates/parser.html
{% extends 'default.html' %}
{% block content %}
<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="parsing">
</form>
{% endblock %}

templates/registration.html
{% extends 'default.html' %}
{% block content %}
    <div class="album py-5 bg-secondary">
        <div class="container">
            <br><br><br>
          <div class="row">
            <div class="col-md-8 order-md-1">
              <h4 class="mb-3">Registration</h4>
              <form action="{% url 'registration' %}" class="needs-validation" novalidate method="POST">
                {% csrf_token %}
                <div class="row">
                  <div class="col-md-6 mb-3">
                    <label for="login">Login</label>
                    <input type="text" class="form-control" id="login" name="login" placeholder="" required>
                    <div class="invalid-feedback">
                      Valid username is required.
                    </div>
                  </div>
                  <div class="col-md-6 mb-3">
                    <label for="email">Email</label>
                    <input type="email" class="form-control" id="email" name="email" placeholder="" required>
                    <div class="invalid-feedback">
                      Valid username is required.
                    </div>
                  </div>
                  <div class="col-md-6 mb-3">
                    <label for="first_name">First name</label>
                    <input type="text" class="form-control" id="first_name" name="first_name" placeholder="" required>
                    <div class="invalid-feedback">
                      Valid username is required.
                    </div>
                  </div>
                  <div class="col-md-6 mb-3">
                    <label for="last_name">Last name</label>
                    <input type="text" class="form-control" id="last_name" name="last_name" placeholder="" required>
                    <div class="invalid-feedback">
                      Valid username is required.
                    </div>
                  </div>
                  <div class="col-md-6 mb-3">
                    <label for="password">Password</label>
                    <input type="password" class="form-control" id="password" name="password" placeholder="" required>
                    <div class="invalid-feedback">
                      Valid password is required.
                    </div>
                  </div>
                  <div class="col-md-6 mb-3">
                    <label for="re-password">Password re-enter</label>
                    <input type="password" class="form-control" id="re-password" name="re-password" placeholder="" required>
                    <div class="invalid-feedback">
                      Valid password is required.
                    </div>
                  </div>
                </div>
                <button class="btn btn-primary btn-lg btn-block" type="submit">Register</button>
              </form>
              <br><br><br><br>
            </div>
          </div>
        </div>
    </div>
        <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="../../assets/js/vendor/popper.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <script src="../../assets/js/vendor/holder.min.js"></script>
    <script>
      // Example starter JavaScript for disabling form submissions if there are invalid fields
      (function() {
        'use strict';

        window.addEventListener('load', function() {
          // Fetch all the forms we want to apply custom Bootstrap validation styles to
          var forms = document.getElementsByClassName('needs-validation');

          // Loop over them and prevent submission
          var validation = Array.prototype.filter.call(forms, function(form) {
            form.addEventListener('submit', function(event) {
              if (form.checkValidity() === false) {
                event.preventDefault();
                event.stopPropagation();
              }
              form.classList.add('was-validated');
            }, false);
          });
        }, false);
      })();
    </script>
{% endblock %}